// Generated by scripts/coreforge/optimize-shots.mjs. Do not edit by hand: change the
// SHOTS table there and rerun it. Captured from goldensdmat.in (the owner's own product)
// in its light theme, with the dated announcement banner and news ticker cropped out and
// no prices in frame. Pure data, so node --test can import it.

export type CoreforgeShotDevice = 'desktop' | 'mobile';

type CoreforgeShotBase = {
  /** Stable key; also the file stem under /images/coreforge/. */
  readonly id: string;
  /** Describes only what the capture shows. */
  readonly alt: string;
  /** The goldensdmat.in page the capture came from, for the outbound link. */
  readonly path: string;
  /** Intrinsic size of the largest rendition. */
  readonly width: number;
  readonly height: number;
  readonly blurDataURL: string;
};

export type CoreforgeDesktopShot = CoreforgeShotBase & {
  readonly device: 'desktop';
  readonly src: { readonly 640: string; readonly 1280: string };
};

export type CoreforgeMobileShot = CoreforgeShotBase & {
  readonly device: 'mobile';
  readonly src: { readonly 390: string; readonly 780: string };
};

export type CoreforgeShot = CoreforgeDesktopShot | CoreforgeMobileShot;

export const COREFORGE_SHOTS_CAPTURED_AT = '2026-09-26';

/** Per-file budget the generator enforces. */
export const COREFORGE_SHOT_MAX_BYTES = 120 * 1024;

export const COREFORGE_SHOT_WIDTHS = {
  desktop: [640, 1280],
  mobile: [390, 780],
} as const;

export const COREFORGE_SHOTS = {
  'welcome-desktop': {
    id: 'welcome-desktop',
    device: 'desktop',
    path: '/welcome',
    alt: 'CoreForge home page on desktop: the headline “The Core Module tests how you think. Your subject module tests how you apply it.”, Start for free and See pricing buttons, and a sample figure-pattern question asking where a marker moves next.',
    width: 1280,
    height: 720,
    src: {
      640: '/images/coreforge/welcome-desktop-640.webp',
      1280: '/images/coreforge/welcome-desktop-1280.webp',
    },
    blurDataURL: 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAB0AQCdASoQAAkAAABMAAALo13vAAD+92mVXURYK5dTtX2VdIHr3lu1/6XP+a+HkAAAAA==',
  },
  'welcome-mobile': {
    id: 'welcome-mobile',
    device: 'mobile',
    path: '/welcome',
    alt: 'CoreForge home page on a phone: the same headline, a note that the Free plan is Core Module practice at easy difficulty in 3-question sets with no card and no expiry, and a Start for free button.',
    width: 780,
    height: 1404,
    src: {
      390: '/images/coreforge/welcome-mobile-390.webp',
      780: '/images/coreforge/welcome-mobile-780.webp',
    },
    blurDataURL: 'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAD0AQCdASoKABIAAABMAAALcyWgHUmqTGwA/vjxfGEGDKYd8x/BN7hkbyQlL+++3MRmlUjTQaVPCMHusqSXXneWcc0gAAAA',
  },
  'demo-desktop': {
    id: 'demo-desktop',
    device: 'desktop',
    path: '/demo',
    alt: 'CoreForge’s public daily demo drill on desktop, question 1 of 10: four 4×4 matrices trace a moving dot, and the answer picks the fifth and sixth matrices from three options each. A badge reads “10 free questions left today”.',
    width: 1280,
    height: 536,
    src: {
      640: '/images/coreforge/demo-desktop-640.webp',
      1280: '/images/coreforge/demo-desktop-1280.webp',
    },
    blurDataURL: 'data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAAAUAQCdASoQAAcAAABMAAANwAD+9qxyksAAAA==',
  },
  'demo-mobile': {
    id: 'demo-mobile',
    device: 'mobile',
    path: '/demo',
    alt: 'The same daily demo drill on a phone: question 1 of 10, four matrices tracing a moving dot in a two-by-two grid, and the first answer option below.',
    width: 780,
    height: 1528,
    src: {
      390: '/images/coreforge/demo-mobile-390.webp',
      780: '/images/coreforge/demo-mobile-780.webp',
    },
    blurDataURL: 'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAD0AQCdASoKABQAAABMAAA+GcHDsIU1sAAA/vjuHJ44NRsr9LN9Fepb1RwFjF9Vqndd9lfrefu0otzj5yF7SbNOQAA=',
  },
  'brain-gym-desktop': {
    id: 'brain-gym-desktop',
    device: 'desktop',
    path: '/brain-gym',
    alt: 'CoreForge Brain Gym page: forty short seeded rounds for speed, attention, memory and reasoning, a card for today’s round with a Play button, and Logic drills including Mini Latin, Sudoku Lite and Odd One Out.',
    width: 1280,
    height: 768,
    src: {
      640: '/images/coreforge/brain-gym-desktop-640.webp',
      1280: '/images/coreforge/brain-gym-desktop-1280.webp',
    },
    blurDataURL: 'data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACUAQCdASoQAAoAAABMAAALnSzFwAAA/vfyc4ycDRPQ4KVa4a88AAAA',
  },
  'modules-desktop': {
    id: 'modules-desktop',
    device: 'desktop',
    path: '/modules',
    alt: 'CoreForge dMAT modules page: it explains that the dMAT is the Core Module plus exactly one subject module, lists facts such as 90 minutes per module, and offers a Find my module button for the “Which module do I need?” wizard.',
    width: 1280,
    height: 640,
    src: {
      640: '/images/coreforge/modules-desktop-640.webp',
      1280: '/images/coreforge/modules-desktop-1280.webp',
    },
    blurDataURL: 'data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAAB0AQCdASoQAAgAAABMAAALc9VGyAD++PoLyetXW5am+8a6K6zZp1H7lFQAAA==',
  },
  'pricing-desktop': {
    id: 'pricing-desktop',
    device: 'desktop',
    path: '/pricing',
    alt: 'Top of the CoreForge Pro page: the headline “One upgrade. The complete dMAT.”, a summary of what Pro adds, and the line “Start on the Free plan — no card needed.”',
    width: 1280,
    height: 424,
    src: {
      640: '/images/coreforge/pricing-desktop-640.webp',
      1280: '/images/coreforge/pricing-desktop-1280.webp',
    },
    blurDataURL: 'data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAAB0AQCdASoQAAUAAABMAAALrID/6AD+92lM+ympvMW/SOWXBc20wAAA',
  },
} as const satisfies Record<string, CoreforgeShot>;

export type CoreforgeShotId = keyof typeof COREFORGE_SHOTS;

export const COREFORGE_SHOT_LIST: readonly CoreforgeShot[] = Object.values(COREFORGE_SHOTS);

/** The largest rendition, for next/image (which builds its own srcset) or a plain src. */
export function shotSrc(shot: CoreforgeShot): string {
  return shot.device === 'desktop' ? shot.src[1280] : shot.src[780];
}

/** A w-descriptor srcset for a plain <img>; pair it with a sizes attribute. */
export function shotSrcSet(shot: CoreforgeShot): string {
  return shot.device === 'desktop'
    ? `${shot.src[640]} 640w, ${shot.src[1280]} 1280w`
    : `${shot.src[390]} 390w, ${shot.src[780]} 780w`;
}
