#!/usr/bin/env node
// Builds the AI grounding corpus from src/data and src/data/site-copy.ts and
// writes src/data/ai-corpus.json (read by the embed, recall and review scripts
// and by generators; the server rebuilds the same chunks from the same data).
//
//   npm run ai:corpus              rebuild and write
//   npm run ai:corpus -- --check   exit 1 when src/data or site copy changed without a rebuild
//
// The freshness gate compares sourceHash, which covers every chunk except the
// volatile ones rebuilt from build-time fetches (live: and facts:), so the
// prebuild's GitHub and LeetCode refresh never trips it.

import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { corpusHash, stableHash, VOLATILE_PREFIXES } from '../../src/lib/ai/corpus.ts';
import { CORPUS_PATH, loadCorpus, ROOT, writeJson } from './lib.mjs';

const check = process.argv.includes('--check');
const rel = path.relative(ROOT, CORPUS_PATH).replaceAll('\\', '/');
const { chunks } = loadCorpus();
const volatile = (id) => VOLATILE_PREFIXES.some((p) => id.startsWith(p));

const doc = {
  version: 1,
  note: 'Generated by scripts/ai/build-corpus.mjs from src/data and src/data/site-copy.ts. Do not edit; run npm run ai:corpus.',
  sourceHash: stableHash(chunks),
  corpusHash: corpusHash(chunks),
  count: chunks.length,
  chunks,
};

if (check) {
  if (!existsSync(CORPUS_PATH)) {
    console.error(`✖ ${rel} is missing. Fix: run \`npm run ai:corpus\` and commit ${rel}.`);
    process.exit(1);
  }
  const committed = JSON.parse(readFileSync(CORPUS_PATH, 'utf8'));
  if (committed.sourceHash === doc.sourceHash) {
    console.log(`✔ ${rel} is fresh (${doc.count} chunks, sourceHash ${doc.sourceHash}).`);
    process.exit(0);
  }
  const before = new Map((committed.chunks ?? []).filter((c) => !volatile(c.id)).map((c) => [c.id, c.hash]));
  const after = new Map(chunks.filter((c) => !volatile(c.id)).map((c) => [c.id, c.hash]));
  const changed = [...after].filter(([id, hash]) => before.has(id) && before.get(id) !== hash).map(([id]) => id);
  const added = [...after.keys()].filter((id) => !before.has(id));
  const removed = [...before.keys()].filter((id) => !after.has(id));
  console.error(`✖ ${rel} is stale: src/data or src/data/site-copy.ts changed without a rebuild.`);
  for (const [label, ids] of [['changed', changed], ['added', added], ['removed', removed]]) {
    if (ids.length) console.error(`  ${label}: ${ids.slice(0, 12).join(', ')}${ids.length > 12 ? `, … (${ids.length})` : ''}`);
  }
  console.error(`  Fix: run \`npm run ai:corpus\` and commit ${rel} (then \`npm run ai:embed\` when a key is available).`);
  process.exit(1);
}

writeJson(CORPUS_PATH, doc);
const selfChars = chunks.filter((c) => c.cls === 'self').reduce((n, c) => n + c.text.length, 0);
console.log(`Wrote ${rel}: ${doc.count} chunks (${selfChars} self chars), sourceHash ${doc.sourceHash}.`);
