#!/usr/bin/env node
// Embeds every corpus chunk once into src/data/ai-vectors.json:
//   { model, dims: 768, entries: { <chunk id>: { hash, s, v } } }
// v is the base64 of the int8-quantised vector and s its scale (about 1 KB per
// vector). Entries are gated by chunk hash, so only new or changed chunks are
// re-embedded, and entries for chunks that no longer exist are dropped.
//
// A probe call runs first: gemini-embedding-2, then gemini-embedding-2-preview
// on a 404. The model that worked is recorded, and the server always embeds
// queries with that recorded model. If it differs from the file's model, every
// chunk is re-embedded (vectors from different models are not comparable).
//
// No key: prints 'skipped: no key' and exits 0. A 429 keeps the existing file
// (plus any batches finished under the same model) and exits 0.
//
//   npm run ai:embed   (node --env-file-if-exists=.env scripts/ai/embed-corpus.mjs)

import path from 'node:path';
import { encodeVec } from '../../src/lib/ai/retrieval.ts';
import { apiKey, EMBED_DIMS, embedTexts, exitSoft, loadCorpus, MODELS, readJson, ROOT, VECTORS_PATH, writeJson } from './lib.mjs';

const BATCH = 32;
const rel = path.relative(ROOT, VECTORS_PATH).replaceAll('\\', '/');

if (!apiKey()) exitSoft('skipped: no key (set GOOGLE_AI_API_KEY to embed the corpus)');

const { chunks } = loadCorpus();
const existing = readJson(VECTORS_PATH, { model: null, dims: EMBED_DIMS, entries: {} });

let model = null;
for (const candidate of MODELS.embedCandidates) {
  const probe = await embedTexts(['probe'], { model: candidate, kind: 'query' });
  if (probe.ok) {
    model = candidate;
    break;
  }
  if (probe.reason === 'quota') exitSoft(`skipped: quota (429) on ${candidate}; kept ${rel} unchanged`);
  if (probe.reason === 'not-found') {
    console.log(`${candidate}: 404, trying the next candidate`);
    continue;
  }
  console.error(`✖ embedding probe failed on ${candidate}${probe.status ? ` (HTTP ${probe.status})` : ''}; ${rel} unchanged`);
  process.exit(1);
}
if (!model) {
  console.error(`✖ none of ${MODELS.embedCandidates.join(', ')} is available; ${rel} unchanged`);
  process.exit(1);
}

const sameModel = existing.model === model && existing.dims === EMBED_DIMS;
const entries = {};
for (const c of chunks) {
  const prev = sameModel ? existing.entries?.[c.id] : undefined;
  if (prev && prev.hash === c.hash) entries[c.id] = prev;
}
const todo = chunks.filter((c) => !entries[c.id]);
const reused = chunks.length - todo.length;
const removed = Object.keys(existing.entries ?? {}).filter((id) => !chunks.some((c) => c.id === id)).length;

function save(note) {
  writeJson(VECTORS_PATH, {
    note: 'Generated by scripts/ai/embed-corpus.mjs. Do not edit; run npm run ai:embed.',
    model,
    dims: EMBED_DIMS,
    entries: Object.fromEntries(Object.keys(entries).sort().map((id) => [id, entries[id]])),
  });
  console.log(note);
}

let embedded = 0;
for (let i = 0; i < todo.length; i += BATCH) {
  const batch = todo.slice(i, i + BATCH);
  const res = await embedTexts(
    batch.map((c) => c.text),
    { model, kind: 'document', titles: batch.map((c) => c.title) },
  );
  if (!res.ok) {
    if (res.reason === 'quota') {
      if (sameModel && embedded > 0) {
        // Keep what finished: those entries are hash-gated and from the recorded model.
        for (const id of Object.keys(existing.entries ?? {})) entries[id] ??= existing.entries[id];
        save(`quota (429) after ${embedded} new vectors; saved them and kept the rest of ${rel}`);
      } else {
        console.log(`skipped: quota (429); kept ${rel} unchanged`);
      }
      process.exit(0);
    }
    console.error(`✖ embedding failed${res.status ? ` (HTTP ${res.status})` : ''} after ${embedded} new vectors; ${rel} unchanged`);
    process.exit(1);
  }
  batch.forEach((c, j) => {
    entries[c.id] = { hash: c.hash, ...encodeVec(res.vectors[j]) };
  });
  embedded += batch.length;
}

const missing = chunks.filter((c) => !entries[c.id]).map((c) => c.id);
if (missing.length) {
  console.error(`✖ ${missing.length} chunks have no vector: ${missing.slice(0, 8).join(', ')}`);
  process.exit(1);
}
save(`Wrote ${rel}: model ${model}, ${chunks.length} vectors (${embedded} embedded, ${reused} reused, ${removed} removed).`);
